# Generated by Django 2.2.4 on 2019-08-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AlterField(
            model_name='photo',
            name='comment',
            field=models.TextField(max_length=200),
        ),
    ]
