# Generated by Django 2.2.4 on 2019-08-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190809_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
